Support some of librabbitmq's finer grained TLS verification routines, available in later versions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4064,7 +4064,8 @@ done
 
 
 
-for ac_header in amqp.h amqp_ssl_socket.h
+
+for ac_header in amqp.h amqp_tcp_socket.h amqp_ssl_socket.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -4214,9 +4215,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
     #include <sys/types.h>
-    #ifdef HAVE_RABBITMQ_AMQP_H
-    # include <amqp.h>
-    #endif
+    #include <amqp.h>
 
 int
 main ()
@@ -4269,7 +4268,7 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 saved_libs="$LIBS"
 LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
-LIBS="$LIBS -lrabbitmq"
+LIBS="$LIBS -lcrypto -lssl -lrabbitmq"
 
 { echo "$as_me:$LINENO: checking for librabbitmq amqp_ssl_socket_new" >&5
 echo $ECHO_N "checking for librabbitmq amqp_ssl_socket_new... $ECHO_C" >&6; }
@@ -4280,9 +4279,9 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-    #ifdef HAVE_RABBITMQ_AMQP_H
-    # include <amqp.h>
-    #endif
+    #include <amqp.h>
+    #include <amqp_tcp_socket.h>
+    #include <amqp_ssl_socket.h>
 
 int
 main ()
@@ -4334,6 +4333,137 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
+
+{ echo "$as_me:$LINENO: checking for librabbitmq amqp_ssl_socket_set_verify_hostname" >&5
+echo $ECHO_N "checking for librabbitmq amqp_ssl_socket_set_verify_hostname... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <amqp.h>
+    #include <amqp_tcp_socket.h>
+    #include <amqp_ssl_socket.h>
+
+int
+main ()
+{
+
+    amqp_socket_t *sock = NULL;
+    (void) amqp_ssl_socket_set_verify_hostname(sock, 1);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMQP_SSL_SOCKET_SET_VERIFY_HOSTNAME 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+{ echo "$as_me:$LINENO: checking for librabbitmq amqp_ssl_socket_set_verify_peer" >&5
+echo $ECHO_N "checking for librabbitmq amqp_ssl_socket_set_verify_peer... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <amqp.h>
+    #include <amqp_tcp_socket.h>
+    #include <amqp_ssl_socket.h>
+
+int
+main ()
+{
+
+    amqp_socket_t *sock = NULL;
+    (void) amqp_ssl_socket_set_verify_peer(sock, 1);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMQP_SSL_SOCKET_SET_VERIFY_PEER 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
 LIBS="$saved_libs"
 
 INCLUDES="$ac_build_addl_includes"
